#!/usr/bin/env python3
from pathlib import Path
import argparse,json,zipfile,tempfile,shutil,hashlib,re,subprocess,sys,importlib.util
ap=argparse.ArgumentParser();ap.add_argument('--target');ap.add_argument('--target-zip');ap.add_argument('--report-dir',default='reports');a=ap.parse_args();tmp=None;archive_bad=[]
if a.target_zip:
 tmp=Path(tempfile.mkdtemp(prefix='vc115_'));z=zipfile.ZipFile(a.target_zip);archive_bad=[n for n in z.namelist() if '__pycache__' in n or '.pytest_cache' in n or n.endswith('.pyc')];z.extractall(tmp);roots=[p for p in tmp.iterdir() if p.is_dir()];R=roots[0] if len(roots)==1 and (roots[0]/'factory-manifest.json').exists() else tmp
else:R=Path(a.target)
out=Path(a.report_dir);out.mkdir(parents=True,exist_ok=True);checks=[]
def ck(i,ok,d=None):checks.append({'id':i,'passed':bool(ok),'detail':d})
def J(r):return json.loads((R/r).read_text(encoding='utf-8'))
def H(p):return hashlib.sha256(p.read_bytes()).hexdigest()
try:
 man=J('factory-manifest.json');M=J('knowledge/binding_methods.json')['methods'];P=J('knowledge/technical_parameters.json')['parameters'];REG=J('provenance/source_registry.json')['sources'];INV=J('provenance/upload_source_inventory.json');C=J('knowledge/method_parameter_contracts_v313.json');E=J('knowledge/external_numeric_parameters_v319.json');S=J('provenance/external_numeric_sources_v319.json');N=J('knowledge/method_numeric_gap_registry_v319.json');B=J('knowledge/book_numeric_parameters_v318.json');FT=J('knowledge/fault_trees.json');CM=J('knowledge/compatibility_matrix.json');bp={x['id']:x for x in P};mids={x['id'] for x in M};sids={x['id'] for x in REG}
 ck('version',man.get('version')=='3.19.0',man.get('version'));ck('methods-105',len(M)==105);ck('params-961',len(P)==961);ck('sources-134',len(REG)==134);ck('top-47',len(INV['top_level_sources'])==47);ck('pending-0',all(x.get('disposition') in {'distilled','merged_duplicate','quarantined','excluded_metadata'} for x in INV['top_level_sources']+INV.get('archive_members',[])))
 skills=sorted((R/'skills').glob('*/SKILL.md'));ck('skills-32',len(skills)==32,len(skills));ck('skills-v319',all(re.search(r'(?m)^version:\s*3\.19\.0\s*$',p.read_text(encoding='utf-8')) for p in skills))
 ck('contracts',len(C['contracts'])==105 and C.get('direct_parameterized_methods')==105 and C.get('zero_direct_parameter_methods')==0);ck('contract-partition',(C.get('numeric_evidence_external_methods_v319'),C.get('numeric_evidence_partial_methods_v319'),C.get('numeric_evidence_unresolved_methods'))==(12,1,1));ck('partition',(N.get('external_numeric_evidence_v317'),N.get('derived_geometry_present'),N.get('book_numeric_evidence_v318'),N.get('external_numeric_evidence_v319'),N.get('partial_numeric_evidence_v319'),N.get('unresolved_after_research'))==(13,8,8,12,1,1));ck('partition-sum',sum([13,8,8,12,1,1])==43 and N.get('method_count')==43)
 ck('v319-sources14',len(S.get('sources',[]))==14);ck('v319-params31',E.get('parameter_count')==31 and len(E.get('parameters',[]))==31);ck('v319-no-prod',all(x.get('production_verified') is False for x in E['parameters']));ck('ref-integrity',all(x.get('source_id') in sids for x in P) and all(mid in mids for x in P for mid in (x.get('applicability') or {}).get('method_ids',[])))
 wu=next(x for x in N['methods'] if x['method_id']=='w-binding');ck('w-zero-honest',wu.get('numeric_parameter_ids')==[] and wu.get('numeric_evidence_status')=='unresolved_after_v319_research' and wu.get('production_default_allowed') is False)
 ez=next(x for x in N['methods'] if x['method_id']=='easy-french-no-glue');ck('easy-partial-honest',ez.get('numeric_evidence_status')=='partial_external_numeric_evidence_v319_added' and ez.get('partial_variant_coverage')=={'covered_variant':'single-sheet X-book','covered_variant_count':1,'grouped_variant_count':4})
 ck('true-french',bp['ext-v319-true-french-chiri']['value']=='1.5');ck('vinyl',bp['ext-v319-vinyl-hardcover-sample-pages']['value']==1950 and bp['ext-v319-vinyl-hardcover-sample-thickness']['value']==90);ck('paper-staple',bp['ext-v319-paper-staple-pkiss10-max-sheets']['value']==10 and bp['ext-v319-paper-staple-pkiss20-max-sheets']['value']==20 and bp['ext-v319-paper-staple-normal-depth-max']['value']==13 and bp['ext-v319-paper-staple-corner-depth-max']['value']==21);ck('wrap',bp['ext-v319-wrap-spine-paper-twist-holes']['value']==[2,3]);ck('book-in-book',bp['ext-v319-book-in-book-subbook-count']['value']==3 and bp['ext-v319-book-in-book-total-pages']['value']==570);ck('nested',bp['ext-v319-nested-book-levels']['value']==3 and bp['ext-v319-nested-book-pages']['value']==20 and bp['ext-v319-nested-book-rotation']['value']==360);ck('fan',bp['ext-v319-fanbook-sample-size']['value']==[2,6] and bp['ext-v319-fanbook-screw-post-length']['value']==0.5);ck('rubber',bp['ext-v319-rubber-hinge-hole-count']['value']==2 and bp['ext-v319-rubber-hinge-band-number']['value']==19);ck('scroll',bp['ext-v319-scroll-mounting-seam']['value']==[2,5] and bp['ext-v319-scroll-heaven-earth-ratio']['value']==[3,2]);ck('album',bp['ext-v319-album-leaf-glass-workplate']['value']==[70,50]);ck('easy-xbook',bp['ext-v319-easy-french-xbook-pages']['value']==8 and bp['ext-v319-easy-french-xbook-sheet-count']['value']==1);ck('back2back',bp['ext-v319-back-to-back-unit-count']['value']==2 and bp['ext-v319-back-to-back-sample-size']['value']==160)
 ck('v318-book17',B.get('parameter_count')==17);ck('v318-kg-preserved',bp['book-v318-foldover-notebook-stock']['unit']=='source_basis_kg');ck('v318-b2-preserved',bp['book-v318-foldover-handcraft-size-range']['value']['max']['source_printed_mm']==[515,420]);ck('fault-65',FT.get('fault_tree_count')==65);ck('compat-162',len(CM.get('matrix',[]))==162)
 refs={p.parent.name:p for p in (R/'references/subskills').glob('*/SKILL.md')} if (R/'references/subskills').exists() else {}
 if refs:ck('root-ref-skill-hash',all(p.parent.name in refs and H(p)==H(refs[p.parent.name]) for p in skills))
 if (R/'installable/HenghuaBookBindingExpert/skills').exists():
  I=R/'installable/HenghuaBookBindingExpert';isk={p.parent.name:p for p in (I/'skills').glob('*/SKILL.md')};iref={p.parent.name:p for p in (I/'references/subskills').glob('*/SKILL.md')};ck('embedded-install-skill-hash',all(p.parent.name in isk and p.parent.name in iref and H(p)==H(isk[p.parent.name])==H(iref[p.parent.name]) for p in skills))
 elif refs:ck('standalone-skill-hash',all(p.parent.name in refs and H(p)==H(refs[p.parent.name]) for p in skills))
 def L(n):
  p=R/'scripts'/f'{n}.py';sp=importlib.util.spec_from_file_location(n,p);m=importlib.util.module_from_spec(sp);sp.loader.exec_module(m);return m
 if (R/'scripts/production_readiness_gate.py').exists():
  pg=L('production_readiness_gate').assess();ck('production-truth',pg.get('status')=='BLOCKED_AWAITING_REAL_DATA' and pg.get('production_ready') is False,pg.get('status'))
  rr=L('technical_parameter_resolver').resolve(ids=['ext-v319-paper-staple-pkiss20-max-sheets'],production=True,context={});ck('v319-prod-block',bool(rr.get('production_release_blockers')))
 if (R/'tests').exists():
  pr=subprocess.run([sys.executable,'-m','pytest','-q'],cwd=R,capture_output=True,text=True,timeout=120);ck('pytest',pr.returncode==0,pr.stdout[-1000:])
  for sc in ['run_v318_book_numeric_evals.py','run_v319_remaining_numeric_evals.py','validate_package.py','check_installable_parity.py']:
   pr=subprocess.run([sys.executable,'scripts/'+sc],cwd=R,capture_output=True,text=True,timeout=90);ck(sc,pr.returncode==0,(pr.stdout+pr.stderr)[-900:])
 else:
  ck('installable-no-tests',True);ck('installable-no-cache',not archive_bad,archive_bad[:10])
except Exception as e:ck('validator-exception',False,repr(e))
rep={'validator_version':'1.15.0','target_version':locals().get('man',{}).get('version'),'total':len(checks),'passed':sum(x['passed'] for x in checks),'failed':sum(not x['passed'] for x in checks),'ok':all(x['passed'] for x in checks),'checks':checks,'failures':[x for x in checks if not x['passed']]};(out/'VALIDATION_CENTER_V115_REPORT.json').write_text(json.dumps(rep,ensure_ascii=False,indent=2)+'\n',encoding='utf-8');(out/'VALIDATION_CENTER_V115_REPORT.md').write_text(f"# Validation Center v1.15.0\n\n- Result: **{'PASS' if rep['ok'] else 'FAIL'}**\n- Checks: **{rep['passed']}/{rep['total']}**\n- Target: **{rep['target_version']}**\n",encoding='utf-8');print(json.dumps(rep,ensure_ascii=False,indent=2));
if tmp:shutil.rmtree(tmp,ignore_errors=True)
sys.exit(0 if rep['ok'] else 1)
